### ISSUE TITLE
历史文章请求间隔不会触发风控么

### ISSUE THREAD

**Issue by dragonlayout** [Zzzz0zzzZ/py-spider-for-wechat#2]
https://github.com/Zzzz0zzzZ/py-spider-for-wechat/blob/dadd15caa56de74ea034deb1edbee147a129cacf/utils/getAllUrls.py#LL30C15-L30C15

请求间隔 2s 测试不会触发风控么, 我自己测试会报错

`err_msg: "freq control", ret: 200013 `

**Comment by Zzzz0zzzZ** [comment]
您好，在短时间内大量爬取文章是会触发的，只能在几小时后才能再爬取了。目前对于单个账号来说，我还没有找到更好的解决方法，如果您有好的建议，欢迎交流讨论！
