### ISSUE TITLE
是否可以增加按照时间段下载公众号上的文章？是否可以多个公众号同时抓取文章？

### ISSUE THREAD

**Issue by SomberOfShadow** [Zzzz0zzzZ/py-spider-for-wechat#3]
1. 可以增加一个feature: 按照时间段下载公众号上的文章？作者觉得呢？
2. 可以增加一个feature: 多个公众号同时抓取

ps: 作者的代码写的清晰简洁易懂，不过ui部分暂时还没细看，正好在帮朋友做这个公众号抓取的事情，作者的代码真是雪中送炭啊！感谢感谢！

**Comment by Zzzz0zzzZ** [comment]
谢谢，ui部分的代码是通过qt creator生成后稍作修改的。新feature会在有空时补充，并合入主分支，谢谢建议！
